Update deploy-production.yml

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -28,20 +28,22 @@ jobs:
       fail-fast: false
     runs-on: self-hosted
     steps:
-      #- name: Set up Git
-      #  run: |
-      #    git config --global user.email "actions@github.com"
-      #    git config --global user.name "GitHub Actions"
+      - name: Set up Git
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
       - name: Switch to production branch
         uses: actions/checkout@v4
         with:
           ref: production-build
       - name: Fast-forward production build
         run: |
-          if ! git pull --ff-only origin test-build; then
-            echo "Could not fast-forward; resetting (hard)"
-            git reset --hard origin/test-build
-          fi 
+          if ! git pull origin test-build; then
+            if ! git pull --ff-only origin test-build; then
+              echo "Could not fast-forward; resetting (hard)"
+              git reset --hard origin/test-build
+            fi
+          fi  
       - name: Push changes into production build
         run: |
           git push
