Update deploy-production.yml

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -28,17 +28,20 @@ jobs:
       fail-fast: false
     runs-on: self-hosted
     steps:
-      - name: Set up Git
-        run: |
-          git config --global user.email "actions@github.com"
-          git config --global user.name "GitHub Actions"
+      #- name: Set up Git
+      #  run: |
+      #    git config --global user.email "actions@github.com"
+      #    git config --global user.name "GitHub Actions"
       - name: Switch to production branch
         uses: actions/checkout@v4
         with:
           ref: production-build
-      - name: Fast-forward production build || hard reset
+      - name: Fast-forward production build
         run: |
-          git pull --ff-only origin test-build || git reset --hard origin/test-build 
+          if ! git pull --ff-only origin test-build; then
+            echo "Could not fast-forward; resetting (hard)"
+            git reset --hard origin/test-build
+          fi 
       - name: Push changes into production build
         run: |
           git push
